// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RosterApp.Infrastructure;

#nullable disable

namespace RosterApp.Infrastructure.Migrations
{
    [DbContext(typeof(RosterDbContext))]
    [Migration("20260820055238_Phase5StaffSwapRequests")]
    partial class Phase5StaffSwapRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RosterApp.Domain.Auditing.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogEntries");
                });

            modelBuilder.Entity("RosterApp.Domain.Rostering.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseRatePerHour")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UnpaidBreakMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "ShiftDate");

                    b.HasIndex("VenueId", "ShiftDate");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("RosterApp.Domain.Rostering.SwapRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManagerDecisionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("RequestingStaffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool?>("TargetStaffAccepted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("TargetStaffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequestingStaffId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("TargetStaffId");

                    b.HasIndex("VenueId")
                        .HasFilter("\"Status\" = 'Pending'");

                    b.ToTable("SwapRequests");
                });

            modelBuilder.Entity("RosterApp.Domain.Staffing.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("StaffMemberId", "StartDate");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("RosterApp.Domain.Staffing.StaffMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("MaxWeeklyHours")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SupabaseUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SupabaseUserId")
                        .IsUnique()
                        .HasFilter("\"SupabaseUserId\" IS NOT NULL");

                    b.HasIndex("OrganisationId", "Email")
                        .IsUnique();

                    b.HasIndex("OrganisationId", "Phone")
                        .IsUnique()
                        .HasFilter("\"Phone\" IS NOT NULL");

                    b.ToTable("StaffMembers", t =>
                        {
                            t.HasCheckConstraint("CK_StaffMembers_Phone_E164", "\"Phone\" ~ '^\\+[1-9]\\d{6,14}$'");
                        });
                });

            modelBuilder.Entity("RosterApp.Domain.Staffing.StandingUnavailability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IncludesAfternoon")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludesEvening")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludesMorning")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StaffMemberId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("StandingUnavailabilities");
                });

            modelBuilder.Entity("RosterApp.Domain.Tenancy.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupabaseUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("SupabaseUserId")
                        .IsUnique();

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("RosterApp.Domain.Tenancy.ManagerVenueAccess", b =>
                {
                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("ManagerId", "VenueId");

                    b.HasIndex("VenueId");

                    b.ToTable("ManagerVenueAccesses");
                });

            modelBuilder.Entity("RosterApp.Domain.Tenancy.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("RosterApp.Domain.Tenancy.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ForecastSalesTarget")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("RosterApp.Domain.Rostering.Shift", b =>
                {
                    b.HasOne("RosterApp.Domain.Tenancy.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("RosterApp.Domain.Rostering.AwardBreakdownLine", "AwardBreakdown", b1 =>
                        {
                            b1.Property<Guid>("ShiftId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)");

                            b1.Property<decimal>("Hours")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<decimal>("RatePerHour")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)");

                            b1.HasKey("ShiftId", "Id");

                            b1.ToTable("ShiftAwardBreakdownLines", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.OwnsMany("RosterApp.Domain.Rostering.ComplianceViolation", "ComplianceViolations", b1 =>
                        {
                            b1.Property<Guid>("ShiftId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<bool>("Acknowledged")
                                .HasColumnType("boolean");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("OverrideReason")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Severity")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.HasKey("ShiftId", "Id");

                            b1.ToTable("ShiftComplianceViolations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.Navigation("AwardBreakdown");

                    b.Navigation("ComplianceViolations");
                });

            modelBuilder.Entity("RosterApp.Domain.Rostering.SwapRequest", b =>
                {
                    b.HasOne("RosterApp.Domain.Rostering.Shift", null)
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RosterApp.Domain.Tenancy.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RosterApp.Domain.Staffing.LeaveRequest", b =>
                {
                    b.HasOne("RosterApp.Domain.Staffing.StaffMember", null)
                        .WithMany()
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RosterApp.Domain.Staffing.StaffMember", b =>
                {
                    b.OwnsMany("RosterApp.Domain.Staffing.StaffMemberVenueAssignment", "VenueAssignments", b1 =>
                        {
                            b1.Property<Guid>("StaffMemberId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("VenueId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.HasKey("StaffMemberId", "VenueId");

                            b1.HasIndex("VenueId");

                            b1.ToTable("StaffMemberVenueAssignments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberId");
                        });

                    b.Navigation("VenueAssignments");
                });

            modelBuilder.Entity("RosterApp.Domain.Staffing.StandingUnavailability", b =>
                {
                    b.HasOne("RosterApp.Domain.Staffing.StaffMember", null)
                        .WithMany()
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RosterApp.Domain.Tenancy.Manager", b =>
                {
                    b.HasOne("RosterApp.Domain.Tenancy.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RosterApp.Domain.Tenancy.ManagerVenueAccess", b =>
                {
                    b.HasOne("RosterApp.Domain.Tenancy.Manager", null)
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RosterApp.Domain.Tenancy.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RosterApp.Domain.Tenancy.Venue", b =>
                {
                    b.HasOne("RosterApp.Domain.Tenancy.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
