// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RosterApp.Infrastructure;

#nullable disable

namespace RosterApp.Infrastructure.Migrations
{
    [DbContext(typeof(RosterDbContext))]
    [Migration("20260825040633_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RosterApp.Domain.Auditing.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogEntries");
                });

            modelBuilder.Entity("RosterApp.Domain.AwardConfig.AwardCalculationRateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AwardId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CasualLoadingPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AwardId")
                        .IsUnique()
                        .HasDatabaseName("IX_AwardCalculationRateVersions_AwardId_Active")
                        .HasFilter("\"EffectiveToUtc\" IS NULL");

                    b.ToTable("AwardCalculationRateVersions");
                });

            modelBuilder.Entity("RosterApp.Domain.AwardConfig.AwardClassificationDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AwardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AwardId");

                    b.ToTable("AwardClassificationDefinitions");
                });

            modelBuilder.Entity("RosterApp.Domain.AwardConfig.AwardConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AwardId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CasualLoadingPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByStaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PayPeriodCutoffDay")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("SuperannuationRatePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AwardId");

                    b.HasIndex("VenueId")
                        .IsUnique()
                        .HasDatabaseName("IX_AwardConfigurations_VenueId_Active")
                        .HasFilter("\"EffectiveToUtc\" IS NULL");

                    b.HasIndex("VenueId", "EffectiveFromUtc");

                    b.ToTable("AwardConfigurations");
                });

            modelBuilder.Entity("RosterApp.Domain.AwardConfig.AwardDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AwardCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AwardCode")
                        .IsUnique();

                    b.ToTable("AwardDefinitions");
                });

            modelBuilder.Entity("RosterApp.Domain.AwardConfig.AwardRate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AwardClassificationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseHourlyRate")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("CasualLoadingPercentMin")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AwardClassificationId")
                        .IsUnique()
                        .HasDatabaseName("IX_AwardRates_AwardClassificationId_Active")
                        .HasFilter("\"EffectiveToUtc\" IS NULL");

                    b.ToTable("AwardRates");
                });

            modelBuilder.Entity("RosterApp.Domain.AwardConfig.RoleAwardMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AwardClassificationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByStaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AwardClassificationId");

                    b.HasIndex("RoleId")
                        .IsUnique()
                        .HasDatabaseName("IX_RoleAwardMappings_RoleId_Active")
                        .HasFilter("\"EffectiveToUtc\" IS NULL");

                    b.HasIndex("VenueId");

                    b.ToTable("RoleAwardMappings");
                });

            modelBuilder.Entity("RosterApp.Domain.RosterCompliance.PublicHoliday", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsNational")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("State", "Date");

                    b.ToTable("PublicHolidays");
                });

            modelBuilder.Entity("RosterApp.Domain.RosterCompliance.RosterComplianceConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByStaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxShiftLengthMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("MinRestBetweenShiftsMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("MinShiftLengthMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeeklyOvertimeThresholdMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VenueId")
                        .IsUnique()
                        .HasDatabaseName("IX_RosterComplianceConfigurations_VenueId_Active")
                        .HasFilter("\"EffectiveToUtc\" IS NULL");

                    b.HasIndex("VenueId", "EffectiveFromUtc");

                    b.ToTable("RosterComplianceConfigurations");
                });

            modelBuilder.Entity("RosterApp.Domain.RosterCompliance.VenueHolidayOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByStaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("OverrideDate")
                        .HasColumnType("date");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VenueId", "OverrideDate");

                    b.ToTable("VenueHolidayOverrides");
                });

            modelBuilder.Entity("RosterApp.Domain.Rostering.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseRatePerHour")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UnpaidBreakMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "ShiftDate");

                    b.HasIndex("VenueId", "ShiftDate");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("RosterApp.Domain.Rostering.SwapRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManagerDecisionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("RequestingStaffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool?>("TargetStaffAccepted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("TargetStaffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequestingStaffId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("TargetStaffId");

                    b.HasIndex("VenueId")
                        .HasFilter("\"Status\" = 'Pending'");

                    b.ToTable("SwapRequests");
                });

            modelBuilder.Entity("RosterApp.Domain.Staffing.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("StaffMemberId", "StartDate");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("RosterApp.Domain.Staffing.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ColorTag")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByStaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RosterApp.Domain.Staffing.StaffMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxWeeklyHours")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PermissionLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Staff");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("PrimaryRoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupabaseUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryRoleId");

                    b.HasIndex("SupabaseUserId")
                        .IsUnique()
                        .HasFilter("\"SupabaseUserId\" IS NOT NULL");

                    b.HasIndex("OrganisationId", "Email")
                        .IsUnique();

                    b.HasIndex("OrganisationId", "Phone")
                        .IsUnique()
                        .HasFilter("\"Phone\" IS NOT NULL");

                    b.ToTable("StaffMembers", t =>
                        {
                            t.HasCheckConstraint("CK_StaffMembers_Phone_E164", "\"Phone\" ~ '^\\+[1-9]\\d{6,14}$'");
                        });
                });

            modelBuilder.Entity("RosterApp.Domain.Staffing.StandingUnavailability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IncludesAfternoon")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludesEvening")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludesMorning")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StaffMemberId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("StandingUnavailabilities");
                });

            modelBuilder.Entity("RosterApp.Domain.Tenancy.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("RosterApp.Domain.Tenancy.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Abn")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByStaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ForecastSalesTarget")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("RosterApp.Domain.Timekeeping.TimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AdjustmentReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("ClockInAccuracyMetres")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal>("ClockInLatitude")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<decimal>("ClockInLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<DateTime>("ClockInUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ClockOutAccuracyMetres")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal?>("ClockOutLatitude")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<decimal?>("ClockOutLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<DateTime?>("ClockOutUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<int?>("VarianceMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("VarianceStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("StaffId");

                    b.HasIndex("VenueId")
                        .HasFilter("\"VarianceStatus\" = 'Flagged'");

                    b.HasIndex("VenueId", "ClockInUtc");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("RosterApp.Domain.AwardConfig.AwardCalculationRateVersion", b =>
                {
                    b.HasOne("RosterApp.Domain.AwardConfig.AwardDefinition", null)
                        .WithMany()
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("RosterApp.Domain.AwardConfig.PenaltyMultiplier", "PenaltyMultipliers", b1 =>
                        {
                            b1.Property<Guid>("AwardCalculationRateVersionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("Multiplier")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)");

                            b1.Property<string>("PenaltyType")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.HasKey("AwardCalculationRateVersionId", "Id");

                            b1.ToTable("AwardCalculationRatePenaltyMultipliers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AwardCalculationRateVersionId");
                        });

                    b.OwnsMany("RosterApp.Domain.AwardConfig.FlatDollarLoading", "FlatDollarLoadings", b1 =>
                        {
                            b1.Property<Guid>("AwardCalculationRateVersionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("DollarPerHour")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)");

                            b1.Property<string>("PenaltyType")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.HasKey("AwardCalculationRateVersionId", "Id");

                            b1.ToTable("AwardCalculationRateFlatDollarLoadings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AwardCalculationRateVersionId");
                        });

                    b.Navigation("FlatDollarLoadings");

                    b.Navigation("PenaltyMultipliers");
                });

            modelBuilder.Entity("RosterApp.Domain.AwardConfig.AwardClassificationDefinition", b =>
                {
                    b.HasOne("RosterApp.Domain.AwardConfig.AwardDefinition", null)
                        .WithMany()
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RosterApp.Domain.AwardConfig.AwardConfiguration", b =>
                {
                    b.HasOne("RosterApp.Domain.AwardConfig.AwardDefinition", null)
                        .WithMany()
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RosterApp.Domain.Tenancy.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("RosterApp.Domain.AwardConfig.PenaltyRateToggle", "PenaltyToggles", b1 =>
                        {
                            b1.Property<Guid>("AwardConfigurationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("boolean");

                            b1.Property<string>("PenaltyType")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.HasKey("AwardConfigurationId", "Id");

                            b1.ToTable("AwardConfigurationPenaltyToggles", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AwardConfigurationId");
                        });

                    b.Navigation("PenaltyToggles");
                });

            modelBuilder.Entity("RosterApp.Domain.AwardConfig.AwardRate", b =>
                {
                    b.HasOne("RosterApp.Domain.AwardConfig.AwardClassificationDefinition", null)
                        .WithMany()
                        .HasForeignKey("AwardClassificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("RosterApp.Domain.AwardConfig.PenaltyMultiplier", "PenaltyMultipliers", b1 =>
                        {
                            b1.Property<Guid>("AwardRateId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("Multiplier")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)");

                            b1.Property<string>("PenaltyType")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.HasKey("AwardRateId", "Id");

                            b1.ToTable("AwardRatePenaltyMultipliers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AwardRateId");
                        });

                    b.Navigation("PenaltyMultipliers");
                });

            modelBuilder.Entity("RosterApp.Domain.AwardConfig.RoleAwardMapping", b =>
                {
                    b.HasOne("RosterApp.Domain.AwardConfig.AwardClassificationDefinition", null)
                        .WithMany()
                        .HasForeignKey("AwardClassificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RosterApp.Domain.Staffing.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RosterApp.Domain.Tenancy.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RosterApp.Domain.RosterCompliance.RosterComplianceConfiguration", b =>
                {
                    b.HasOne("RosterApp.Domain.Tenancy.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("RosterApp.Domain.RosterCompliance.MealBreakRule", "MealBreakRules", b1 =>
                        {
                            b1.Property<Guid>("RosterComplianceConfigurationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("AfterHoursWorked")
                                .HasPrecision(4, 2)
                                .HasColumnType("numeric(4,2)");

                            b1.Property<int>("BreakDurationMinutes")
                                .HasColumnType("integer");

                            b1.Property<bool>("IsPaid")
                                .HasColumnType("boolean");

                            b1.HasKey("RosterComplianceConfigurationId", "Id");

                            b1.ToTable("RosterComplianceMealBreakRules", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RosterComplianceConfigurationId");
                        });

                    b.OwnsOne("RosterApp.Domain.RosterCompliance.MinorRosterRule", "MinorRules", b1 =>
                        {
                            b1.Property<Guid>("RosterComplianceConfigurationId")
                                .HasColumnType("uuid");

                            b1.Property<TimeOnly>("EarliestStartTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("MinorEarliestStartTime");

                            b1.Property<TimeOnly>("LatestFinishTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("MinorLatestFinishTime");

                            b1.Property<decimal>("MaxDailyHours")
                                .HasPrecision(4, 2)
                                .HasColumnType("numeric(4,2)")
                                .HasColumnName("MinorMaxDailyHours");

                            b1.Property<decimal>("MaxWeeklyHours")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("MinorMaxWeeklyHours");

                            b1.HasKey("RosterComplianceConfigurationId");

                            b1.ToTable("RosterComplianceConfigurations");

                            b1.WithOwner()
                                .HasForeignKey("RosterComplianceConfigurationId");
                        });

                    b.Navigation("MealBreakRules");

                    b.Navigation("MinorRules")
                        .IsRequired();
                });

            modelBuilder.Entity("RosterApp.Domain.RosterCompliance.VenueHolidayOverride", b =>
                {
                    b.HasOne("RosterApp.Domain.Tenancy.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RosterApp.Domain.Rostering.Shift", b =>
                {
                    b.HasOne("RosterApp.Domain.Tenancy.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("RosterApp.Domain.Rostering.AwardBreakdownLine", "AwardBreakdown", b1 =>
                        {
                            b1.Property<Guid>("ShiftId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)");

                            b1.Property<decimal>("Hours")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<decimal>("RatePerHour")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)");

                            b1.HasKey("ShiftId", "Id");

                            b1.ToTable("ShiftAwardBreakdownLines", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.OwnsMany("RosterApp.Domain.Rostering.ComplianceViolation", "ComplianceViolations", b1 =>
                        {
                            b1.Property<Guid>("ShiftId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<bool>("Acknowledged")
                                .HasColumnType("boolean");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("OverrideReason")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Severity")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.HasKey("ShiftId", "Id");

                            b1.ToTable("ShiftComplianceViolations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.Navigation("AwardBreakdown");

                    b.Navigation("ComplianceViolations");
                });

            modelBuilder.Entity("RosterApp.Domain.Rostering.SwapRequest", b =>
                {
                    b.HasOne("RosterApp.Domain.Rostering.Shift", null)
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RosterApp.Domain.Tenancy.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RosterApp.Domain.Staffing.LeaveRequest", b =>
                {
                    b.HasOne("RosterApp.Domain.Staffing.StaffMember", null)
                        .WithMany()
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RosterApp.Domain.Staffing.Role", b =>
                {
                    b.HasOne("RosterApp.Domain.Tenancy.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RosterApp.Domain.Staffing.StaffMember", b =>
                {
                    b.HasOne("RosterApp.Domain.Staffing.Role", null)
                        .WithMany()
                        .HasForeignKey("PrimaryRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("RosterApp.Domain.Staffing.PayRateOverride", "PayRateOverride", b1 =>
                        {
                            b1.Property<Guid>("StaffMemberId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EffectiveFromUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("OverrideEffectiveFromUtc");

                            b1.Property<decimal>("OverrideHourlyRate")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("OverrideHourlyRate");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("OverrideReason");

                            b1.Property<Guid>("SetByStaffMemberId")
                                .HasColumnType("uuid")
                                .HasColumnName("OverrideSetByStaffMemberId");

                            b1.HasKey("StaffMemberId");

                            b1.ToTable("StaffMembers");

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberId");
                        });

                    b.OwnsMany("RosterApp.Domain.Staffing.StaffMemberVenueAssignment", "VenueAssignments", b1 =>
                        {
                            b1.Property<Guid>("StaffMemberId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("VenueId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.HasKey("StaffMemberId", "VenueId");

                            b1.HasIndex("VenueId");

                            b1.ToTable("StaffMemberVenueAssignments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberId");
                        });

                    b.Navigation("PayRateOverride");

                    b.Navigation("VenueAssignments");
                });

            modelBuilder.Entity("RosterApp.Domain.Staffing.StandingUnavailability", b =>
                {
                    b.HasOne("RosterApp.Domain.Staffing.StaffMember", null)
                        .WithMany()
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RosterApp.Domain.Tenancy.Venue", b =>
                {
                    b.HasOne("RosterApp.Domain.Tenancy.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("RosterApp.Domain.Tenancy.TradingHourSession", "TradingHours", b1 =>
                        {
                            b1.Property<Guid>("VenueId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<TimeOnly?>("CloseTime")
                                .HasColumnType("time without time zone");

                            b1.Property<bool>("CrossesMidnight")
                                .HasColumnType("boolean");

                            b1.Property<string>("DayOfWeek")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<bool>("IsClosed")
                                .HasColumnType("boolean");

                            b1.Property<TimeOnly?>("OpenTime")
                                .HasColumnType("time without time zone");

                            b1.Property<string>("SessionLabel")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("VenueId", "Id");

                            b1.ToTable("VenueTradingHours", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VenueId");
                        });

                    b.OwnsOne("RosterApp.Domain.Tenancy.VenueAvailabilitySettings", "AvailabilitySettings", b1 =>
                        {
                            b1.Property<Guid>("VenueId")
                                .HasColumnType("uuid");

                            b1.Property<int>("AdvanceNoticeDays")
                                .HasColumnType("integer")
                                .HasDefaultValue(7)
                                .HasColumnName("AvailabilityAdvanceNoticeDays");

                            b1.Property<string>("SelfServiceMode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasDefaultValue("RequiresApproval")
                                .HasColumnName("AvailabilitySelfServiceMode");

                            b1.HasKey("VenueId");

                            b1.ToTable("Venues");

                            b1.WithOwner()
                                .HasForeignKey("VenueId");
                        });

                    b.OwnsOne("RosterApp.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("VenueId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("Address_Country");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Address_Line1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Address_Line2");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("character varying(4)")
                                .HasColumnName("Address_Postcode");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("Address_State");

                            b1.Property<string>("Suburb")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Address_Suburb");

                            b1.HasKey("VenueId");

                            b1.ToTable("Venues");

                            b1.WithOwner()
                                .HasForeignKey("VenueId");
                        });

                    b.Navigation("Address");

                    b.Navigation("AvailabilitySettings")
                        .IsRequired();

                    b.Navigation("TradingHours");
                });

            modelBuilder.Entity("RosterApp.Domain.Timekeeping.TimeEntry", b =>
                {
                    b.HasOne("RosterApp.Domain.Rostering.Shift", null)
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RosterApp.Domain.Tenancy.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
