<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>RosterApp.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="libphonenumber-csharp" Version="9.0.37" />
  </ItemGroup>

</Project>
